import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";

export default function Home() {
  // useEffect(() => {
  //   const upreach = Upreach.signIn("ahanikotb@gmail.com", "BIGD");
  // }, []);
  return (
    <div>
      <Head>
        <title>Upreach App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div></div>
    </div>
  );
}
